GameOfBreak/Areas/Admin/Models/AccesorioViewModel.cs
using GameOfBreak.Models.GoB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GameOfBreak.Areas.Admin.Models {

    public class AccesorioViewModel {

        public string UPC { get; set; }

        public Accesorio Accesorio { get; set; }

        public Plataforma Plataforma { get; set; }

        public IEnumerable<Plataforma> Plataformas { get; set; }

    }

}

GameOfBreak/Areas/Admin/Models/VideojuegoViewModel.cs
using GameOfBreak.Models.GoB;
using System.Collections.Generic;

namespace GameOfBreak.Areas.Admin.Models {

    public class VideojuegoViewModel {

        public string UPC { get; set; }

        public VideoJuego Videojuego { get; set; }

        public Plataforma Plataforma { get; set; }

        public IEnumerable<Plataforma> Plataformas { get; set; }

        public Desarrolladora Desarrolladora { get; set; }

        public IEnumerable<Desarrolladora> Desarrolladoras { get; set; }

        public Clasificacion Clasificacion { get; set; }

        public IEnumerable<Clasificacion> Clasificaciones { get; set; }

        public Genero Genero { get; set; }

        public IEnumerable<Genero> Generos { get; set; }

    }

}

GameOfBreak/Controllers/ShoppingCartController.cs
using GameOfBreak.Models;
using GameOfBreak.Models.GoB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameOfBreak.Controllers {

    public class ShoppingCartController : Controller {

        private GameOfBreakModel _context;

        public ShoppingCartController () {
            this._context = new GameOfBreakModel();
        }

        // Se muestra el detalle del carrito
        // GET: ShoppingCart
        public ActionResult Index () {

            var shoppingCart = ShoppingCart.GetCarrito(this.HttpContext);

            CarritoViewModel viewModel = null;

            try {

                var idCarrito = Int64.Parse(shoppingCart.ID_CARRITO);

                viewModel = new CarritoViewModel() {
                    idCarrito = idCarrito.ToString(),
                    DetalleCarrito = this._context.DetalleCarrito
                                                  .Where(detCar => detCar.ID_CARRITO == idCarrito)
                                                  .Select(detCar => new DetalleCarritoViewModel() {
                                                      idDetalleCarrito = detCar.ID_DETALLE_CARRITO,
                                                      UPC = detCar.UPC,
                                                      Titulo = this._context.Productos.Where(prod => prod.UPC.Equals(detCar.UPC)).Select(prod => prod.Titulo).FirstOrDefault(),
                                                      Plataforma = this._context.Productos.Where(prod => prod.UPC.Equals(detCar.UPC)).Select(prod => prod.Plataforma).FirstOrDefault(),
                                                      Cantidad = detCar.Cantidad,
                                                      Precio = detCar.Monto,
                                                      Total = (detCar.Cantidad * detCar.Monto)
                                                  })
                                                  .AsEnumerable()
                };

            } catch (Exception) {

                var idCarrito = shoppingCart.ID_CARRITO;

                viewModel = new CarritoViewModel() {
                    idCarrito = idCarrito.ToString(),
                    DetalleCarrito = this._context.DetalleCarritoTemporal
                                                  .Where(detCar => detCar.ID_CARRITO.Equals(idCarrito))
                                                  .Select(detCar => new DetalleCarritoViewModel() {
                                                      idDetalleCarrito = detCar.ID_DETALLE_CARRITO,
                                                      UPC = detCar.UPC,
                                                      Titulo = this._context.Productos.Where(prod => prod.UPC.Equals(detCar.UPC)).Select(prod => prod.Titulo).FirstOrDefault(),
                                                      Plataforma = this._context.Productos.Where(prod => prod.UPC.Equals(detCar.UPC)).Select(prod => prod.Plataforma).FirstOrDefault(),
                                                      Cantidad = detCar.Cantidad,
                                                      Precio = detCar.Monto,
                                                      Total = (detCar.Cantidad * detCar.Monto)
                                                  })
                                                  .AsEnumerable()
                };

            }

            return View(viewModel);

        }

        public ActionResult AgregarAlCarrito (string upc) {

            var correctoUpc = this._context.Productos.Where(prod => prod.UPC.Equals(upc)).Select(prod => prod.UPC).FirstOrDefault();

            if (!String.IsNullOrEmpty(correctoUpc)) {

                var carrito = ShoppingCart.GetCarrito(this.HttpContext);

                carrito.AgregarProducto(upc);

            } else {
                return HttpNotFound("Producto no encontrado");
            }

            return RedirectToAction("Index");

        }

        public ActionResult RemoverDelCarrito (string upc) {

            var correctoUpc = this._context.Productos.Where(prod => prod.UPC.Equals(upc)).Select(prod => prod.UPC).FirstOrDefault();

            if (!String.IsNullOrEmpty(correctoUpc)) {

                var carrito = ShoppingCart.GetCarrito(this.HttpContext);

                carrito.QuitarProducto(upc);

            } else {
                return HttpNotFound("Producto no encontrado");
            }

            return RedirectToAction("Index");

        }

        public ActionResult ConfirmarCompra () {

            if (!User.Identity.IsAuthenticated) {

                return RedirectToAction("Login", "Account");

            }

            var carrito = ShoppingCart.GetCarrito(this.HttpContext);

            carrito.ConfirmarCompra();

            Session[ShoppingCart.KEY_ID_CARRITO] = null;

            return RedirectToAction("Index", "Home");

        }

        [ChildActionOnly]
        public ActionResult CartSummary () {

            var cart = ShoppingCart.GetCarrito(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");

        }

    }

}

GameOfBreak/Controllers/VentaProductoController.cs
using GameOfBreak.Areas.Admin.Models;
using GameOfBreak.Models;
using GameOfBreak.Models.GoB;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GameOfBreak.Controllers {

    public class VentaProductoController : Controller {

        private GameOfBreakModel _context;

        public VentaProductoController() {
            this._context = new GameOfBreakModel();
        }

        protected override void Dispose(bool disposing) {
            this._context = new GameOfBreakModel();
        }

        #region Videojuegos

        // GET: Producto
        public ActionResult Videojuegos(int idConsola, int? idGenero, int? page, int? count) {

            var existeConsola = this._context.Plataforma
                                        .Where(plat => plat.ID_PLATAFORMA == idConsola)
                                        .FirstOrDefault();

            if (existeConsola == null) {
                return HttpNotFound("No existe la consola especificada");
            }

            // Validamos el numero de la pagina
            if (!page.HasValue) {
                page = 1;
            } else if (page <= 0) {
                page = 1;
            }

            // Se obtienen los UPC de los productos con los que cuenta la tienda En Linea en su almacen
            var upc = this._context.Almacen.Where(almacen => almacen.ID_TIENDA == 1).Select(almacen => almacen.UPC).AsEnumerable();

            // Se seleccionan aquellos que son solamente videojuegos
            var listaUpcVideojuegos = this._context.VideoJuego.Where(vj => upc.Contains(vj.UPC))
                                                              .Select(vj => vj.UPC)
                                                              .ToList();

            // Se selecciona aquellos que son de la plataforma especificada
            IEnumerable<string> upcProductos = this._context.RelProductoPlataforma.Where(rel => rel.ID_PLATAFORMA == idConsola
                                                                            && listaUpcVideojuegos.Contains(rel.UPC))
                                                                 .Select(rel => rel.UPC)
                                                                 .ToList();

            count = upcProductos.Count();

            // Obtenemos el total de registros
            //if (!count.HasValue) {
            //}

            // Creamos el Pager
            var pager = new Pager(count.Value, page, 6);

            //Obtenemos el detalle de cada producto, en este caso, videojuegos

            var videojuegos = this._context.VideoJuego
                                           .Include(vj => vj.Clasificacion)
                                           .Include(vj => vj.Genero)
                                           .Include(vj => vj.Desarrolladora)
                                           .Where(videojuego => upcProductos.Contains(videojuego.UPC))
                                           .OrderByDescending(videojuego => videojuego.FechaSalida)
                                           .Skip((pager.CurrentPage - 1) * 6)
                                           .Take(6)
                                           //.Select(videojuego => new ProductoVentaViewModel() {
                                           //    UPC = videojuego.UPC,
                                           //    Nombre = videojuego.Nombre,
                                           //    Estatus = this._context.Estatus.Where(estatus => estatus.ID_ESTATUS == (this._context.Almacen
                                           //                                                                                         .Where(almacen => almacen.UPC.Equals(videojuego.UPC)
                                           //                                                                                                        && almacen.ID_TIENDA == 1)
                                           //                                                                                         .Select(almacen => almacen.ID_ESTATUS)
                                           //                                                                                         .FirstOrDefault()))
                                           //                                   .FirstOrDefault(),
                                           //    Precio = this._context.Almacen.Where(almacen => almacen.UPC.Equals(videojuego.UPC) && almacen.ID_TIENDA == 1).Select(almacen => almacen.Precio).FirstOrDefault(),
                                           //    Clasificacion = videojuego.Clasificacion.Clasificacion1,
                                           //    Genero = videojuego.Genero.Genero1,
                                           //    Desarrolladora = videojuego.Desarrolladora.Desarrolladora1,
                                           //    FechaSalida = videojuego.FechaSalida,
                                           //    Ruta = this._context.RepositorioMultimedia.Where(rep => rep.ID_TIPO_MULTIMEDIA == 1 && rep.UPC.Equals(videojuego.UPC)).FirstOrDefault().Ruta
                                           //})
                                           .ToList();

            var vjSelectos = videojuegos.Select(vj => new ProductoVentaViewModel() {
                UPC = vj.UPC,
                Nombre = vj.Nombre,
                Estatus = this._context.Almacen.Include(a => a.Estatus).FirstOrDefault(a => a.UPC.Equals(vj.UPC) && a.ID_TIENDA == 1).Estatus.Estatus1,
                Precio = this._context.Almacen.FirstOrDefault(a => a.UPC.Equals(vj.UPC) && a.ID_TIENDA == 1).Precio,
                Clasificacion = vj.Clasificacion.Clasificacion1,
                Genero = vj.Genero.Genero1,
                Desarrolladora = vj.Desarrolladora.Desarrolladora1,
                FechaSalida = vj.FechaSalida,
                Ruta = this._context.RepositorioMultimedia.FirstOrDefault(rep => rep.ID_TIPO_MULTIMEDIA == 1 && rep.UPC.Equals(vj.UPC))?.Ruta
            }).ToList();

            var viewModel = new PaginationViewModel<ProductoVentaViewModel>() {
                Items = vjSelectos,
                Pager = pager
            };

            ViewBag.Plataforma = existeConsola.Plataforma1;
            ViewBag.IdConsola = idConsola;

            return View(viewModel);

        }

        public ActionResult VerDetalleVideojuego(string upc) {

            var videojuego = this._context.VideoJuego
                                          .Include(vj => vj.Genero)
                                          .Include(vj => vj.Clasificacion)
                                          .Include(vj => vj.Desarrolladora)
                                          .Where(vj => vj.UPC.Equals(upc))
                                          .FirstOrDefault();

            if (videojuego == null) {
                return HttpNotFound("No se ha encontrado el producto especificado.");
            }

            var viewModel = new VideojuegoDetalleViewModel() {
                Videojuego = videojuego,
                Precio = this._context.Almacen.Where(almacen => almacen.UPC.Equals(videojuego.UPC) && almacen.ID_TIENDA == 1).Select(almacen => almacen.Precio).FirstOrDefault(),
                Rating = this._context.Rating.Where(rating => rating.UPC.Equals(videojuego.UPC)).FirstOrDefault(),
                Repositorio = this._context.RepositorioMultimedia.Include(rep => rep.TipoMultimedia).Where(rep => rep.UPC.Equals(videojuego.UPC)).AsEnumerable(),
                Consola = this._context.Plataforma.Where(plat => plat.ID_PLATAFORMA == (this._context.RelProductoPlataforma.Where(rel => rel.UPC.Equals(videojuego.UPC)).Select(rel => rel.ID_PLATAFORMA).FirstOrDefault())).FirstOrDefault(),
                Estatus = this._context.Estatus.Where(estatus => estatus.ID_ESTATUS == (this._context.Almacen.Where(al => al.UPC.Equals(videojuego.UPC) && al.ID_TIENDA == 1).Select(al => al.ID_ESTATUS).FirstOrDefault())).FirstOrDefault()
            };

            return View(viewModel);

        }

        #endregion

        #region Accesorios

        public ActionResult Accesorios(int idConsola, int? idGenero, int? page, int? count) {

            var existeConsola = this._context.Plataforma
                                        .Where(plat => plat.ID_PLATAFORMA == idConsola)
                                        .FirstOrDefault();

            if (existeConsola == null) {
                return HttpNotFound("No existe la consola especificada");
            }

            // Validamos el numero de la pagina
            if (!page.HasValue) {
                page = 1;
            } else if (page <= 0) {
                page = 1;
            }

            // Se obtienen los UPC de los productos con los que cuenta la tienda En Linea en su almacen
            var upc = this._context.Almacen.Where(almacen => almacen.ID_TIENDA == 1).Select(almacen => almacen.UPC).AsEnumerable();

            // Se seleccionan aquellos que son solamente videojuegos
            var listaUpcAccesorios = this._context.Accesorio.Where(vj => upc.Contains(vj.UPC)).Select(vj => vj.UPC).AsEnumerable();

            // Se selecciona aquellos que son de la plataforma especificada
            IEnumerable<string> upcPoductos = this._context.RelProductoPlataforma.Where(rel => rel.ID_PLATAFORMA == idConsola
                                                                            && listaUpcAccesorios.Contains(rel.UPC))
                                                                 .Select(rel => rel.UPC)
                                                                 .AsEnumerable(); ;

            count = upcPoductos.Count();

            // Obtenemos el total de registros
            //if (!count.HasValue) {
            //}

            // Creamos el Pager

GameOfBreak/Views/VentaProducto/Accesorios.cshtml
@model GameOfBreak.Models.PaginationViewModel<GameOfBreak.Models.ProductoVentaViewModel>
@{
    ViewBag.Title = "Accesorios";
    var plataforma = ViewBag.Plataforma;
    byte count = 0;
    var pager = Model.Pager;
    var idConsola = ViewBag.IdConsola;
}

<h2>Videojuegos</h2>

<ol class="breadcrumb">
    <li>@Html.ActionLink("Game Of Break", "Index", "Home")</li>
    <li class="active">@plataforma</li>
</ol>

<div class="row">
    @foreach (var item in Model.Items) {

        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="@item.Ruta" alt="Imagen" />
                <div class="caption">
                    <h2>@Html.ActionLink(item.Nombre, "VerDetalleAccesorio", "VentaProducto", new { upc = item.UPC }, null)</h2>
                    <h6>@item.Estatus</h6>
                    <h4>Precio: @String.Format("{0:C}", item.Precio)</h4>
                    <h5>Fecha de lanzamiento: @String.Format("{0: dd/MM/yyyy}", item.FechaSalida)</h5>
                    @Html.ActionLink("Agregar al carrito", "AgregarAlCarrito", "ShoppingCart", new { upc = item.UPC }, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>

        count++;
        if (count == 2) {
            <div class="clearfix visible-sm-block"></div>
        } else if (count == 3) {
            count = 0;
            <div class="clearfix visible-md-block visible-lg-block"></div>
        }

    }
</div>

<div class="row">

    <nav aria-label="Page navigation" class="col-sm-6">
        <ul class="pagination">

            @for (int i = pager.StartPage; i <= pager.EndPage; i++) {
                <li class="@(i == pager.CurrentPage ? " active": ")" )">@Html.ActionLink(i.ToString(), "Accesorios", "VentaProducto", new { idConsola = idConsola, page = i, count = pager.TotalItems }, null)</li>
            }

        </ul>
    </nav>

    <div class="col-sm-6">
        Total de registros obtenidos:
        <div class="badge">
            @pager.TotalItems
        </div>
    </div>

</div>

GameOfBreak/Views/VentaProducto/VerCompras.cshtml
@model GameOfBreak.Models.PaginationViewModel<GameOfBreak.Areas.Admin.Models.VentaViewModel>
@{
    ViewBag.Title = "Compras";
    //var tienda = ViewBag.Tienda as GameOfBreak.Models.GoB.Tienda;
    var ventas = Model.Items;
    var pager = Model.Pager;

}

<h2>Compras</h2>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>Numero de la Tienda</th>
            <th>Nombre de la Tienda</th>
            <th>Nombre del Empleado</th>
            <th>Usuario del Empleado</th>
            <th>Nombre del Cliente</th>
            <th>Usuario</th>
            <th>Fecha</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in ventas) {
            <tr>
                <td>@item.Tienda.NumeroTienda</td>
                <td>@item.Tienda.Nombre</td>
                @if (item.Empleado.Id.Equals(GameOfBreak.Models.Roles.UsuarioAdministradorID)) {
                    <td>No aplica</td>
                    <td>No aplica</td>
                } else {
                    <td>@(item.Empleado.PrimerNombre + " " + item.Empleado.ApellidoPaterno)</td>
                    <td>@(item.Empleado.UserName)</td>
                }
                <td>@(item.Cliente.PrimerNombre + " " + item.Cliente.ApellidoPaterno)</td>
                <td>@(item.Cliente.UserName)</td>
                <td>@String.Format("{0:yyyy/MM/dd}", item.Venta.Fecha)</td>
                <td>
                    @Html.ActionLink("Detalle de la compra", "DetalleCompra", "VentaProducto", new { idVenta = item.Venta.ID_VENTA }, new { @class = "btn btn-default" })
                </td>
            </tr>
        }
    </tbody>

</table>


<div class="row">

    <nav aria-label="Page navigation">
        <ul class="pagination">

            @for (int i = pager.StartPage; i <= pager.EndPage; i++) {
                <li class="@(i == pager.CurrentPage ? " active": ")" )">@Html.ActionLink(i.ToString(), "VerCompras", "VentaProducto", new { page = i, count = pager.TotalItems }, null)</li>
            }

        </ul>
    </nav>

    <div>
        Total de registros obtenidos:
        <div class="badge">
            @pager.TotalItems
        </div>
    </div>

</div>

GameOfBreak/Views/VentaProducto/VerDetalleAccesorio.cshtml
@model GameOfBreak.Models.AccesorioDetalleViewModel
@{

    var accesorio = Model.Videojuego;
    var estatus = Model.Estatus;
    var precio = Model.Precio;
    var consola = Model.Consola;
    var active = true;
    ViewBag.Title = accesorio.Nombre;

}

<h2>@accesorio.Nombre</h2>

@* Breadcrumb *@
<ol class="breadcrumb">
    <li>@Html.ActionLink("Game Of Break", "Index", "Home")</li>
    <li>@Html.ActionLink(consola.Plataforma1, "Videojuegos", "VentaProducto", new { idConsola = consola.ID_PLATAFORMA }, null)</li>
    <li class="active">@accesorio.Nombre</li>
</ol>

@* Carousel *@
<div class="panel panel-default">
    <div class="panel-heading">Imagenes</div>
    <div class="panel-body">
        @if (Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 3).Count() > 0) {
            <div id="imgcarousel" class="carousel" data-ride="carousel">
                <div class="carousel-inner">
                    <ol class="carousel-indicators">
                        @for (int i = 0; i < Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 3).Count(); i++) {
                            <li data-target="#imgcarousel" data-slide-to="@i.ToString()" class="@(active ? "active" : "")"></li>
                        }
                    </ol>

                    @foreach (var image in Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 3)) {

                        <div class="item @(active ? "active" : "")">
                            <img src="@Url.Content(image.Ruta)" class="img-responsive center-block" width="560" height="560" />
                        </div>

                        <a class="left carousel-control" href="#imgcarousel" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>

                        <a class="right carousel-control" href="#imgcarousel" data-slide="next">
                            <span class="icon-next"></span>
                        </a>

                        {
                            active = false;
                        }


                    }
                </div>
            </div>
        }
    </div>
</div>

@* Datos y detalles del videojuego *@
<div class="panel panel-default">
    <div class="panel-heading">Detalles</div>
    <div class="panel-body">
        <div class="thumbnail">
            @*<img src="..." alt="...">*@
            <div class="caption">
                <h2>@accesorio.Nombre</h2>
                <h6>@estatus.Estatus1</h6>
                <h4>Precio: @String.Format("{0 :C}", precio)</h4>
                <h5>Fecha de lanzamiento: @String.Format("{0: dd/MM/yyyy}", accesorio.FechaSalida)</h5>
                <p>Descripcion: @accesorio.Descripcion</p>
                @Html.ActionLink("Agregar al carrito", "AgregarAlCarrito", "ShoppingCart", new { upc = accesorio.UPC }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

@* Estadisticas de evaluacion *@
<div class="panel panel-default">
    <div class="panel-heading">Estadisticas</div>
    <div class="panel-body">
    </div>
</div>


@* Video *@
<div class="panel panel-default">
    <div class="panel-heading">Video</div>
    <div class="panel-body">
        <div class="bs-example" data-example-id="responsive-embed-16by9-iframe-youtube">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe width="560" height="315" src="@(Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 4).LastOrDefault() != null ? Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 4).LastOrDefault().Ruta : "")" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>

GameOfBreak/Views/VentaProducto/VerDetalleVideojuego.cshtml
@model GameOfBreak.Models.VideojuegoDetalleViewModel
@{

    var consola = Model.Consola;
    var videojuego = Model.Videojuego;
    var rating = Model.Rating;
    var estatus = Model.Estatus;
    var precio = Model.Precio;
    var active = true;
    ViewBag.Title = videojuego.Nombre;

}

<h2>@videojuego.Nombre</h2>

@* Breadcrumb *@
<ol class="breadcrumb">
    <li>@Html.ActionLink("Game Of Break", "Index", "Home")</li>
    <li>@Html.ActionLink(consola.Plataforma1, "Videojuegos", "VentaProducto", new { idConsola = consola.ID_PLATAFORMA }, null)</li>
    <li class="active">@videojuego.Nombre</li>
</ol>

@* Carousel *@
<div class="panel panel-default">
    <div class="panel-heading">Imagenes</div>
    <div class="panel-body">
        @if (Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 3).Count() > 0) {
            <div id="imgcarousel" class="carousel" data-ride="carousel">
                <div class="carousel-inner">
                    <ol class="carousel-indicators">
                        @for (int i = 0; i < Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 3).Count(); i++) {
                            <li data-target="#imgcarousel" data-slide-to="@i.ToString()" class="@(active ? "active" : "")"></li>
                        }
                    </ol>

                    @foreach (var image in Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 3)) {

                        <div class="item @(active ? "active" : "")">
                            <img src="@Url.Content(image.Ruta)" class="img-responsive center-block" width="560" height="560" />
                        </div>

                        <a class="left carousel-control" href="#imgcarousel" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>

                        <a class="right carousel-control" href="#imgcarousel" data-slide="next">
                            <span class="icon-next"></span>
                        </a>

                        {
                            active = false;
                        }


                    }
                </div>
            </div>
        }
    </div>
</div>

@* Datos y detalles del videojuego *@
<div class="panel panel-default">
    <div class="panel-heading">Detalles</div>
    <div class="panel-body">
        <div class="thumbnail">
            @*<img src="..." alt="...">*@
            <div class="caption">
                <h2>@videojuego.Nombre</h2>
                <h6>@estatus.Estatus1</h6>
                <h3>@videojuego.Desarrolladora.Desarrolladora1</h3>
                <h4>Precio: @String.Format("{0 :C}", precio)</h4>
                <h5>Clasificación: @videojuego.Clasificacion.Clasificacion1</h5>
                <h5>Genero: @videojuego.Genero.Genero1</h5>
                <h5>Fecha de lanzamiento: @String.Format("{0: dd/MM/yyyy}", videojuego.FechaSalida)</h5>
                <p>Descripcion: @videojuego.Descripcion</p>
                @Html.ActionLink("Agregar al carrito", "AgregarAlCarrito", "ShoppingCart", new { upc = videojuego.UPC }, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>

@* Estadisticas de evaluacion *@
<div class="panel panel-default">
    <div class="panel-heading">Estadisticas</div>
    <div class="panel-body">
    </div>
</div>


@* Video *@
<div class="panel panel-default">
    <div class="panel-heading">Video</div>
    <div class="panel-body">
        <div class="bs-example" data-example-id="responsive-embed-16by9-iframe-youtube">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe width="560" height="315" src="@(Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 4).LastOrDefault() != null ? Model.Repositorio.Where(rep => rep.ID_TIPO_MULTIMEDIA == 4).LastOrDefault().Ruta : "")" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
    </div>
</div>


@section scripts {

    <script>
        $('.carousel').carousel({
            interval: 2000
        })
    </script>
}

GameOfBreak/Views/VentaProducto/Videojuegos.cshtml
@model GameOfBreak.Models.PaginationViewModel<GameOfBreak.Models.ProductoVentaViewModel>
@{
    ViewBag.Title = "Videojuegos";
    var plataforma = ViewBag.Plataforma;
    byte count = 0;
    var pager = Model.Pager;
    var idConsola = ViewBag.IdConsola;
}

<h2>Videojuegos</h2>

<ol class="breadcrumb">
    <li>@Html.ActionLink("Game Of Break", "Index", "Home")</li>
    <li class="active">@plataforma</li>
</ol>

<div class="row">
    @foreach (var item in Model.Items) {

        <div class="col-sm-6 col-md-4">
            <div class="thumbnail">
                <img src="@item.Ruta" alt="Imagen" />
                <div class="caption">
                    <h2>@Html.ActionLink(item.Nombre, "VerDetalleVideojuego", "VentaProducto", new { upc = item.UPC }, null)</h2>
                    <h6>@item.Estatus</h6>
                    <h3>@item.Desarrolladora</h3>
                    <h4>Precio: @String.Format("{0:C}", item.Precio)</h4>
                    <h5>Clasificación: @item.Clasificacion</h5>
                    <h5>Género: @item.Genero</h5>
                    <h5>Fecha de lanzamiento: @String.Format("{0: dd/MM/yyyy}", item.FechaSalida)</h5>
                    @Html.ActionLink("Agregar al carrito", "AgregarAlCarrito", "ShoppingCart", new { upc = item.UPC }, new { @class = "btn btn-default" })
                </div>
            </div>
        </div>

        count++;
        if (count == 2) {
            <div class="clearfix visible-sm-block"></div>
        } else if (count == 3) {
            count = 0;
            <div class="clearfix visible-md-block visible-lg-block"></div>
        }

    }
</div>

@if (idConsola != 0) {

    <div class="row">

        <nav aria-label="Page navigation" class="col-sm-6">
            <ul class="pagination">

                @for (int i = pager.StartPage; i <= pager.EndPage; i++) {
                    <li class="@(i == pager.CurrentPage ? " active": ")" )">@Html.ActionLink(i.ToString(), "Videojuegos", "VentaProducto", new { idConsola = idConsola, page = i, count = pager.TotalItems }, null)</li>
                }

            </ul>
        </nav>

        <div class="col-sm-6">
            Total de registros obtenidos:
            <div class="badge">
                @pager.TotalItems
            </div>
        </div>

    </div>

}